### PR TITLE
Supply exit status code on exit

### PR DESCRIPTION
**Pull request by jwcxz**
Adds error checking for:
    - missing or incorrect input file
    - missing output file option
    - error during evaluation

If the output is successfully produced, returns the status code 0.
Otherwise returns 1.

### CODE REVIEW

**Comment by jwcxz** [comment]
Use case is that this helps with anyone using Wavedrom in, for example, a Makefile, so that make stops executing if the diagram failed to build.

**Comment by drom** [comment]
@jwcxz great! Thank you for the code. `bin/wavedrom-cli.js` is actually build by `build-wavedrom-cli.sh` script. So you source changes should probably go to `src/p5.js` first. Could you fix it?

**Comment by jwcxz** [comment]
@drom no problem; sorry that I got a bit confused there.  In addition to making the changes to `src/p5.js`, shall I also run `build-wavedrom-cli.sh` and include the newly-generated `bin/wavedrom-cli.js` as part of the commit?

Thanks for your guidance.

**Comment by jwcxz** [comment]
I've done both, but as separate commits.  I can revert the last commit if desired.

**Comment by drom** [comment]
@jwcxz You did it very well! Thanks for the contribution.

**Pull request merged**
